name: chauffeurs_app
description: "Application mobile pour les chauffeurs SOS"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  
  # 📱 UI et fonctionnalités
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  another_flushbar: ^1.12.30
  
  # 🌐 API et stockage
  http: ^1.2.1
  shared_preferences: ^2.2.2  # Unique entry for shared_preferences
  
  # 🗺️ Maps et localisation
  google_maps_flutter: ^2.6.0
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  
  # 🔧 Services et utilitaires
  flutter_background_service: ^5.0.5
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.3.0
  url_launcher: ^6.3.1
  
  # 🔔 Notifications
  flutter_local_notifications: ^17.2.4
  flutter_local_notifications_linux: ^4.0.0+1
  flutter_local_notifications_platform_interface: ^7.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  # Si tu utilises des assets (images, fonts, etc.), ajoute-les ici
  assets:
    - assets/images/logo.png
    - assets/images/background.jpg
    - assets/images/app_icon.png
